services:
  smartmargin:
    image: postgres
    container_name: smartmargin
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER:admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smartmargin
  
  frontend:
    build:
      context: ../smartmargin-frontend/
      dockerfile: Dockerfile
    container_name: "smartmargin_frontend"
    ports:
      - "5173:5173"
    volumes:
      - ../smartmargin-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - smartmargin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    command: >
      bash -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - catcollectorspa
volumes:
  postgres_data: